### ISSUE TITLE
日程・時間を決める

### ISSUE THREAD

**Issue by hyamatter** [ScienSlack/meeting#1]

**Comment by t-uda** [comment]
「懇親会」の時間について．

バッファ作る意味も込めて，一時間休み入れる方がいいと思います．他所のイベントで，17 時終了 18 時懇親会開始のはずが，LT とかで時間が押しに押して 17:50 終了 18 時即開始は厳しいなぁ，ということがありました．

質問をなるべく制御してオンタイムで行く鋼の意思で運営するなら，バッファ想定で一時間休み入れて 18 時開始でいいとは思います．

**Comment by hyamatter** [comment]
やはりバッファは大事ですね。
18時から19時半くらいかな。

**Comment by hyamatter** [comment]
スケジュールは完璧に決まってるのでCloseします
